version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"