server:
  port: 8081
  servlet:
    context-path: /task-manager

spring:
  application:
    name: TaskManager

  liquibase:
    change-log: db/changelog/changelog-master.yaml

  datasource:
    username: user
    password: pass1234
    url: jdbc:postgresql://localhost:5432/task_manager
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true